dsa/urls.py
from django.contrib import admin
from django.urls import path, include


from first import views
#from pizza.urls import url as pizza_urls

urlpatterns = [
    path('admin/', admin.site.urls),

    #cust
    path('', views.index, name='index'),

    path('pizza', include('pizza.urls', namespace='pizza')),
]

pizza/urls.py
from django.urls import path

from pizza.views import create, view, close, stats

urlpatterns=[
path('/create', create, name='create_pizza'),
path('/view/(?P<pizza_order_id>[0-9]+)', view, name='view'),
path('/close/(?P<pizza_order_id>[0-9]+)', close, name='close'),
path('/stats', stats, name='stats'),
]

first/models.py
from django.db import models

# Create your models here.

pizza/models.py
from django.db import models
from django.cont import settings
from django.db.models import Manager
from django.utils import timezone
from django.db.models.signal import post_save, m2m_changed
from django.utils.text import get_valid_filename


# Create your models here.


class Address(models.Model):
	full=models.CharField(max_length=150)


	def __str__(self):
		return str(self.full)

class PizzaIngridient(models.Model):
	name=models.CharField(max_length=50)


	def __str__(self):
		return str(self.name)


class PizzaMenuItem(models.Model):
	name = models.CharField(max_length=50)
	ingridients = models.ManyToManyField(
		'PizzaIngridient',
		related_name='menu_Items'
		)


	def __str__(self):
		return str(self.name)


class PizzaSize(models.Model):
	LARGE=('XL', 'LARGE')
	MEDIUM=('MD', 'MEDIUM')
	SMALL=('SM', 'SMALL')
	__all = (LARGE, MEDIUM, SMALL)


	size=models.CharField(max_length=2, choices=__all)


	def __str__(self):
		return str(self.size)


class PizzaOrderManager(Manager):
	def get_queryset(self, **kwargs):
		return super(PizzaOrderManager, self).get_queryset().filter(
				delivered=True
			)


class PizzaOrder(models.Model):
	kind = models.ForeignKey('PizzaMenuItem', related_name='pizzas')
	size = models.ForeignKey('PizzaSize', related_name='pizzas')
	delivery = models.ForeignKey('Address', related_name='pizzas')


	extra = models.ManyToManyField(
		'PizzaIngridiient', blank=True, related_name='pizzas_extra')
	exclude = models.ManyToManyField('PizzaIngridient', blank=True)
	comment = models.CharField(max_length=140, blank = True)


	delivered = models.BooleanField(default=False)
	date_created = models.DateTimeField(default=timezone.now())
	date_delivered = models.DateTimeField(default=None, blank=True)


	objects = Manager()
	delivered_manager = PizzaOrderManager()


	def mark_delivered(self, commit=True):
		self.delivered=True
		self.date_delivered = timezone.now()
		if commit:
			self.save()

	def save(self, **kwargs):
		if not self.pk:
			print('Creating new Pizzaorddr')
		else:
			print('updating existing pizza order')

		super(PizzaOrder, self).save(**kwargs)

	def __str__(self):
		return 'PizzaOreder [%s]' % self.id

pizza/forms.py
from django import forms
from django.core.exceptions import ValidationError

from pizza.models import PizzaOrder, Address


class DeliveryForm(forms.ModelsForm):
	class Meta:
		model = Address
		fields = ['full',]


class PizzaOrderForm(forms.ModelForm):
	class Meta:
		model = PizzaOrder
		exclude = [
			'delivered',
			'date_created', 
			'date_delivered',
			'delivery',
			]

	def clean(self):
		data = self.cleaned_data
		excluded = data['exclude']


		errors=[]
		for item in excluded:
			if item in data['extra']:
				errors.append(str(item))


		if errors:
			raise ValidationError(
				'Ingridient [{}] are in extras and exludes'.format(', '.join(errors)))
			return data


	def save(self, commit=True, delivery=None):
		if delivery is None:
			raise ValueError('Delivery was not set')

		inst = super().save(commit=False)
		inst.delivery= delivery
		if commit:
			inst.save()

		return inst

first/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def index(request):
	if request.method=='GET':
		return HttpResponse('Hello world')

pizza/views.py
from django.shortcuts import render, redirect, get_object__or_404
from django.core.urlresolvers import reverse
from django.db import transaction
from django.db.models import Avg, Count, F
from django.http import HttpResponse, Http404
from django.utils import timezone

from pizza.models import PizzaOrder, PizzaSize
from pizza.forms import PizzaOrderForm, DeliveryForm

# Create your views here.
def createold(request):
	if request.method=='GET':
		return render(request, 'create.html')


def index(request):
	if request.method == 'GET':
		pizzas = PizzaOrder.objects.all()
		return (request, 'index.html',{'pizzas':pizzas})
	return HttpResponse(status=405)

def create(request):
	if request.method=='GET':
		c = {
		'pizza_form': PizzaOrderForm(),
		'delivery_form': DeliveryForm(),
		}
		return render(request, 'create.html', c)

	elif reuest.method == 'POST':
		pizza_form = pizzaOrderForm(request.POST)
		delivery_from = DeliveryForm(request.POST)

		if pizza_form.is_valid() and delivery_from.is_valide():
			with transaction.atomic():
				delivery = delivery_from.save()
				pizza = pizza_from.save(delivery = delivery)
				pizza_form.save_m2m()

			return redirect(reverse('pizza:view', kwargs={
				'pizza_order_id': pizza.pk
				}))
		else:
			c={
			'pizza_form': pizza_form,
			'delivery_form': delivery_from,
			}
			return render(request, 'create.html', c)
	return HttpResponse(status=405)


def view(request, pizza_order_id):
	if request.method == 'GET':

		pizza = PizzaOrder.objects.filter(
			id = pizza_order_id).select_related().prefetch_related(
			'kind_ingridients', 'exclude', 'extra').first()

		if not pizza:
			raise Http404

		return render(request, pizza_order_id):
	return HttpResponse(status=405)


def close(request, pizza_order_id):
	if request.method == 'GET':
		try:
			pizza = get_object_or_404(PizzaOrder, id=pizza_order_id)
			pizza.mark_delivered()

			return redirect(reverse('pizza:view', kwargs={
					'pizza_order_id': pizza.pk
				}))
		except Pizza.order.DoesnotExist:
			return HttpResponse('does not exists')
	return HttpResponse(status=405)



def stats(request):
	if request.method == 'GET':
		count = PizzaOrder.objects.count()
		average_extras = PizzaOrder.objects.all().annotate(
			extra_count=Count('extra')).aggregate(result=Avg('extra_count'))

		small_size = PizzaSize.objects.get(size=PizzaSize.SMALL[0])

		print(list(small_size))
		query = {
		'date_created_day': today.day,
		'date_created_month': today.month,
		'date_created_year': today.year,
		}
		today_pizzas = PizzaOrder.objects.filter(**query).count()
		today_delivered = PizzaOrder.delivered_manager.filter(**query).count()

pizza/templates/create.html
<!DOCTYPE html>
<html>
<head>
	<title>piiza order</title>
{% block content %}

<from action="{% url 'pizza:create' %}" method="POST">
	{% csrf_token %}

	<h2> Addres</h2>
	{{ delivery_form.as_p }}

	<hr>

	<h2>Pizza</h2>
	{{ pizza_form.as_p }}

	<input type="submit" value="Submit">
</from>
{% endblock %}
<!--</head>
<body>
	<form action="/pizza/create" method="POST">

		<H1>Address</H1>
		<input type="text" id="address" name="address">
		<label for="address">full:</label>

		<hr>

		<h1>Pizza</h1><br>
		<h2>kind</h2><br>


		<input type="radio" name="kind" value="type1">peperoni<br>
		<input type="radio" name="kind" value="type2">margarita<br>
		<input type="radio" name="kind" value="type3">four ham<br>
		<input type="radio" name="kind" value="type4">all-in<br>
		<br><br>


		<h2>size</h2>
		<input type="radio" name="size" value="s">small<br>
		<input type="radio" name="size" value="m">medium<br>
		<input type="radio" name="size" value="l">large<br>
		<input type="radio" name="size" value="xl">extra large<br>
		<br><br>


		<h2>extra</h2>
		<select name="extra" size="4" multiple>
			<option value="ham">ham</option>
			<option value="tomato">tomato</option>
			<option value="peperonis">peperonis</option>
			<option value="olives">olives</option>
			<option value="cheese">cheese</option>
			<option value="mushrooms">mushrooms</option>
			<option value="peper">peper</option>
		</select>
		<br><br>


		<h2>exclude</h2>
		<select name="exclude" size="4" multiple>
			<option value="ham">ham</option>
			<option value="tomato">tomato</option>
			<option value="peperonis">peperonis</option>
			<option value="olives">olives</option>
			<option value="cheese">cheese</option>
			<option value="mushrooms">mushrooms</option>
			<option value="peper">peper</option>
		</select>
		<br><br>

		<h2>comment</h2>
		<textarea name="comment"></textarea>
		<br><br>
		<input type="submit" value="submit">

	</form>
</body>
</html>
-->

pizza/templates/index.html
{% block content %}
	<a href="{% url 'pizza:create' %}">create new</a>

	<ul>
		{% for pizza in pizzas %}
			<li><a href="{% url 'pizza:view' pizza.id %}">{{pizza}}</a></li>
		{% endfor %}
	</ul>

{% endblock %}

pizza/templates/view.html
{% block content %}

<p>Name: {{ pizza.kind }}</p>
<p>Size: {{ pizza.size }}</p>
<p>Delivery address: {{ pizza.delivery.full }}</p>

<p>Ingridients:</p>
<ul>
	{% for ingridient in pizza.kind.ingridients.all %}
		{% if ingridient not in pizza.exclude.all %}
			<li>{{ ingridients.name }}</li>
		{% endif %}
	{% endfor %}
</ul>

<p>Extra</p>
<ul>
	{% for ingridient in pizza.extra.all %}
		<li>{{ ingridient.name }}</li>
	{% endfor %}
</ul>

<p>Excluded</p>
<ul>
	{% for ingridients in pizza.extra.all %}
		<li>{{ ingridient.name }}</li>
	{% endfor %}
</ul>

<p>Comment: {{ pizza.comment }}</p>

<hr>

<p>Status: {{ pizza.delivered|yesno:"Delivered,Delivering,kek" }}</p>
<p>Created: {{ pizza.date_created }}</p>
<p>Delivered: {{ pizza.date_delivered|default_if_None:"Not yet"}}</p>

{% if not pizza.delivered %}
	<a href="{% url 'pizza:close' pizza.id %}">Mark delivered</a>
{% endif %}

{% endblock %}